### ISSUE TITLE
Investigate focal failures

### ISSUE THREAD

**Issue by dragomirp** [canonical/pgbouncer-operator#368]
Tests deploying on focal started failing with:
```
 unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install Traceback (most recent call last):
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install   File "./src/charm.py", line 24, in <module>
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install     from charms.postgresql_k8s.v0.postgresql_tls import PostgreSQLTLS
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install   File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/postgresql_k8s/v0/postgresql_tls.py", line 27, in <module>
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install     from charms.tls_certificates_interface.v2.tls_certificates import (
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install   File "/var/lib/juju/agents/unit-pgbouncer-1/charm/lib/charms/tls_certificates_interface/v2/tls_certificates.py", line 284, in <module>
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install     from cryptography import x509
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install   File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/cryptography/x509/__init__.py", line 7, in <module>
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install     from cryptography.x509 import certificate_transparency, verification
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install   File "/var/lib/juju/agents/unit-pgbouncer-1/charm/venv/cryptography/x509/certificate_transparency.py", line 11, in <module>
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install     from cryptography.hazmat.bindings._rust import x509 as rust_x509
unit-pgbouncer-1: 02:00:18 WARNING unit.pgbouncer/1.install ImportError: libssl.so.3: cannot open shared object file: No such file or directory
unit-pgbouncer-1: 02:00:18 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
```

E.g. https://github.com/canonical/pgbouncer-operator/actions/runs/10913826467/job/30291214527

**Comment by dragomirp** [comment]
Issue is caused by prebuilt charms being complied against the wrong SOs. I will temporarily disable the cached builds for PGB. Issue to track the cached whls: https://github.com/canonical/charmcraftcache-hub/issues/111

**Comment by dragomirp** [comment]
Workaround merged
